import { Client } from '@/types';

export const CLIENTS_SEED: Client[] = [
  {
    "id": "client-animo-bread-cinere",
    "companyName": "ANIMO BREAD CINERE",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 5664000,
    "createdAt": "2026-05-22T08:37:22.253Z",
    "notes": ""
  },
  {
    "id": "client-atsumaru-bar",
    "companyName": "ATSUMARU BAR",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 414000,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-atsumaru-izakaya",
    "companyName": "ATSUMARU IZAKAYA",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 5059500,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-bakmie-taat",
    "companyName": "BAKMIE TAAT",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 3689950,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-bapak-archie",
    "companyName": "BAPAK ARCHIE",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 4403850,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-bapak-damar",
    "companyName": "BAPAK DAMAR",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 835750,
    "createdAt": "2026-05-22T08:37:22.256Z",
    "notes": ""
  },
  {
    "id": "client-central-kitchen-seindonesia-cibinong",
    "companyName": "CENTRAL KITCHEN SEINDONESIA CIBINONG",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 43140000,
    "createdAt": "2026-05-22T08:37:22.256Z",
    "notes": ""
  },
  {
    "id": "client-central-kitchen-seindonesia-kiat-ananda",
    "companyName": "CENTRAL KITCHEN SEINDONESIA KIAT ANANDA",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 1358946600,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-cuan-yu",
    "companyName": "CUAN YU",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 0,
    "createdAt": "2026-05-22T08:37:22.256Z",
    "notes": ""
  },
  {
    "id": "client-daily-bread-cafe",
    "companyName": "DAILY BREAD CAFE",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 1065250,
    "createdAt": "2026-05-22T08:37:22.256Z",
    "notes": ""
  },
  {
    "id": "client-daily-bread-epicentrum",
    "companyName": "DAILY BREAD EPICENTRUM",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 18050186,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-daily-bread-tebet",
    "companyName": "DAILY BREAD TEBET",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 2983750,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-demie-bakmie-bintaro",
    "companyName": "DEMIE BAKMIE BINTARO",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 11023280,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-demie-bakmie-blok-m",
    "companyName": "DEMIE BAKMIE BLOK M",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 13643860,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-demie-bakmie-central-kitchen",
    "companyName": "DEMIE BAKMIE CENTRAL KITCHEN",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 263262540,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-demie-bakmie-cilandak",
    "companyName": "DEMIE BAKMIE CILANDAK",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 17846490,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-demie-bakmie-katering",
    "companyName": "DEMIE BAKMIE KATERING",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 1671300,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-demie-bakmie-kemang",
    "companyName": "DEMIE BAKMIE KEMANG",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 18754930,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-demie-bakmie-margonda",
    "companyName": "DEMIE BAKMIE MARGONDA",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 11228050,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-demie-bakmie-menteng",
    "companyName": "DEMIE BAKMIE MENTENG",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 29075442,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-demie-bakmie-senopati",
    "companyName": "DEMIE BAKMIE SENOPATI",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 16531980,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-demie-bakmie-store",
    "companyName": "DEMIE BAKMIE STORE",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 15666000,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-demie-bakmie-tebet",
    "companyName": "DEMIE BAKMIE TEBET",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 21033850,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-demie-catering",
    "companyName": "DEMIE CATERING",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 220000,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-fresh-box",
    "companyName": "FRESH BOX",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 545763050,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-goat-coffee",
    "companyName": "GOAT COFFEE",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 6003550,
    "createdAt": "2026-05-22T08:37:22.256Z",
    "notes": ""
  },
  {
    "id": "client-headquarter-bar---pool",
    "companyName": "HEADQUARTER BAR & POOL",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 432000,
    "createdAt": "2026-05-22T08:37:22.256Z",
    "notes": ""
  },
  {
    "id": "client-holycow-by-chef-afit---alam-sutera",
    "companyName": "HOLYCOW BY CHEF AFIT - ALAM SUTERA",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 13211000,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-holycow-by-chef-afit---batu-tulis",
    "companyName": "HOLYCOW BY CHEF AFIT - BATU TULIS",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 5108500,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-holycow-by-chef-afit---batutulis",
    "companyName": "HOLYCOW BY CHEF AFIT - BATUTULIS",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 3098000,
    "createdAt": "2026-05-22T08:37:22.256Z",
    "notes": ""
  },
  {
    "id": "client-holycow-by-chef-afit---bekasi",
    "companyName": "HOLYCOW BY CHEF AFIT - BEKASI",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 47636000,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-holycow-by-chef-afit---bintaro",
    "companyName": "HOLYCOW BY CHEF AFIT - BINTARO",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 16782500,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-holycow-by-chef-afit---cibubur",
    "companyName": "HOLYCOW BY CHEF AFIT - CIBUBUR",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 8923500,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-holycow-by-chef-afit---cijantung",
    "companyName": "HOLYCOW BY CHEF AFIT - CIJANTUNG",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 57652000,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-holycow-by-chef-afit---citos",
    "companyName": "HOLYCOW BY CHEF AFIT - CITOS",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 15829000,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-holycow-by-chef-afit---foodtruck",
    "companyName": "HOLYCOW BY CHEF AFIT - FOODTRUCK",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 3225000,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-holycow-by-chef-afit---gading-serpong",
    "companyName": "HOLYCOW BY CHEF AFIT - GADING SERPONG",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 8057000,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-holycow-by-chef-afit---kalibata-city",
    "companyName": "HOLYCOW BY CHEF AFIT - KALIBATA CITY",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 10275500,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-holycow-by-chef-afit---kalimalang",
    "companyName": "HOLYCOW BY CHEF AFIT - KALIMALANG",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 12727000,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-holycow-by-chef-afit---kebon-jeruk",
    "companyName": "HOLYCOW BY CHEF AFIT - KEBON JERUK",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 16547250,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-holycow-by-chef-afit---kelapa-gading",
    "companyName": "HOLYCOW BY CHEF AFIT - KELAPA GADING",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 10457000,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-holycow-by-chef-afit---mampang",
    "companyName": "HOLYCOW BY CHEF AFIT - MAMPANG",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 5826500,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-holycow-by-chef-afit---pik",
    "companyName": "HOLYCOW BY CHEF AFIT - PIK",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 5089500,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-holycow-by-chef-afit---wolter",
    "companyName": "HOLYCOW BY CHEF AFIT - WOLTER",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 10796500,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-holycow-heritage-arjuna",
    "companyName": "HOLYCOW HERITAGE ARJUNA",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 8502660,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-holycow-warehouse-stored",
    "companyName": "HOLYCOW WAREHOUSE STORED",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 634000,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-holycow-warehouse-wolter",
    "companyName": "HOLYCOW WAREHOUSE WOLTER",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 291000,
    "createdAt": "2026-05-22T08:37:22.257Z",
    "notes": ""
  },
  {
    "id": "client-ibu-debby",
    "companyName": "IBU DEBBY",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 1016000,
    "createdAt": "2026-05-22T08:37:22.257Z",
    "notes": ""
  },
  {
    "id": "client-ibu-euis",
    "companyName": "IBU EUIS",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 310800,
    "createdAt": "2026-05-22T08:37:22.257Z",
    "notes": ""
  },
  {
    "id": "client-ibu-syifa",
    "companyName": "IBU SYIFA",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 332000,
    "createdAt": "2026-05-22T08:37:22.257Z",
    "notes": ""
  },
  {
    "id": "client-jankendon",
    "companyName": "JANKENDON",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 1767750,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-kedai-mie-tjap-1000-tahun-bintaro",
    "companyName": "KEDAI MIE TJAP 1000 TAHUN BINTARO",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 8457000,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-kedai-mie-tjap-1000-tahun-ck-bintaro",
    "companyName": "KEDAI MIE TJAP 1000 TAHUN CK BINTARO",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 40387200,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-kedai-mie-tjap-1000-tahun-ck-bintaro--raker-",
    "companyName": "KEDAI MIE TJAP 1000 TAHUN CK BINTARO (RAKER)",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 209100,
    "createdAt": "2026-05-22T08:37:22.257Z",
    "notes": ""
  },
  {
    "id": "client-kedai-mie-tjap-1000-tahun-scbd",
    "companyName": "KEDAI MIE TJAP 1000 TAHUN SCBD",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 22581100,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-kedai-mie-tjap-1000-tahun-senopati",
    "companyName": "KEDAI MIE TJAP 1000 TAHUN Senopati",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 7316600,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-kenara-catering",
    "companyName": "KENARA CATERING",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 3616750,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-kilo-astha",
    "companyName": "KILO ASTHA",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 1612600,
    "createdAt": "2026-05-22T08:37:22.257Z",
    "notes": ""
  },
  {
    "id": "client-kilo-trinity",
    "companyName": "KILO TRINITY",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 1033250,
    "createdAt": "2026-05-22T08:37:22.257Z",
    "notes": ""
  },
  {
    "id": "client-kualinari-catering",
    "companyName": "KUALINARI CATERING",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 1730000,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-kyo-coffee-astha",
    "companyName": "KYO COFFEE ASTHA",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 2617000,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-kyo-coffee-jatiwaringin",
    "companyName": "KYO COFFEE JATIWARINGIN",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 68390500,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-meat-a-meat-steak",
    "companyName": "MEAT A MEAT STEAK",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 48706600,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-midaz-senayan-golf",
    "companyName": "MIDAZ SENAYAN GOLF",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 4491000,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-mitra-boga-kreasi-prima",
    "companyName": "MITRA BOGA KREASI PRIMA",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 4000000,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-mookie",
    "companyName": "MOOKIE",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 27394532,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-ms-jackson",
    "companyName": "MS JACKSON",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 13446650,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-narasa",
    "companyName": "NARASA",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 12162200,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-pepr-burger-senayan",
    "companyName": "PEPR BURGER SENAYAN",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 25024000,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-pepr-burger-uf-cipete",
    "companyName": "PEPR BURGER UF CIPETE",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 26752000,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-pt-mitra-boga-kreasi-prima",
    "companyName": "PT MITRA BOGA KREASI PRIMA",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 3400000,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-pt-mitraboga-kreasi-prima",
    "companyName": "PT MITRABOGA KREASI PRIMA",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 15800000,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-resto-seto",
    "companyName": "RESTO SETO",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 2669685,
    "createdAt": "2026-05-22T08:37:22.257Z",
    "notes": ""
  },
  {
    "id": "client-rivareno-plaza-senayan",
    "companyName": "RIVARENO PLAZA SENAYAN",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 13984000,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-rivareno-urban-forest-cipete",
    "companyName": "RIVARENO URBAN FOREST CIPETE",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 11332440,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-rni",
    "companyName": "RNI",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 4683000,
    "createdAt": "2026-05-22T08:37:22.257Z",
    "notes": ""
  },
  {
    "id": "client-shots-coffee",
    "companyName": "SHOTS COFFEE",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 205096300,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-simpang-raya",
    "companyName": "SIMPANG RAYA",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 29204000,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-sliced-pizza-bintaro",
    "companyName": "SLICED PIZZA BINTARO",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 11170700,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-sliced-pizza-blok-m",
    "companyName": "SLICED PIZZA BLOK M",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 31124450,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-sliced-pizza-cibis",
    "companyName": "SLICED PIZZA CIBIS",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 58558050,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-sliced-pizza-cikini",
    "companyName": "SLICED PIZZA CIKINI",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 143600,
    "createdAt": "2026-05-22T08:37:22.257Z",
    "notes": ""
  },
  {
    "id": "client-sliced-pizza-pondok-pinang",
    "companyName": "SLICED PIZZA PONDOK PINANG",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 9256600,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-sliced-pizza-scbd",
    "companyName": "SLICED PIZZA SCBD",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 10766850,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-ssi-group",
    "companyName": "SSI GROUP",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 1014900,
    "createdAt": "2026-05-22T08:37:22.257Z",
    "notes": ""
  },
  {
    "id": "client-sulu-adityawarman",
    "companyName": "SULU ADITYAWARMAN",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 1248900,
    "createdAt": "2026-05-22T08:37:22.257Z",
    "notes": ""
  },
  {
    "id": "client-the-halal-guys-smb",
    "companyName": "THE HALAL GUYS SMB",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 6730185,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  },
  {
    "id": "client-vietnamese-pho-24-noodle",
    "companyName": "VIETNAMESE PHO 24 NOODLE",
    "picName": "",
    "email": "",
    "phone": "",
    "address": "",
    "paymentTermDays": 30,
    "totalOrderJanMay": 72582200,
    "createdAt": "2026-05-22T06:37:54.203Z",
    "notes": ""
  }
];
