import type { Metadata } from "next";
import { Sora, Geist_Mono } from "next/font/google";
import "./globals.css";
import GlobalAnnouncement from "@/components/layout/global-announcement";
import StoreSync from "@/components/providers/store-sync";

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import DevOverlay from "@/components/dev-overlay";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${sora.variable} ${geistMono.variable} font-sans antialiased`}
        suppressHydrationWarning
      >
        <GlobalAnnouncement />
        <StoreSync />
        {children}
        <DevOverlay />
      </body>
    </html>
  );
}

